version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: todo-postgresql
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - '5050:5432'
    volumes:
      - /var/lib/postgresql/data
      # - ./todo-server/db-init:/docker-entrypoint-initdb.d/
    networks:
      - default
  server:
    build:
      context: todo-server
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - '0.0.0.0:8081:8080'
    volumes:
      - ./todo-server:/app
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PORT: ${PORT}
    command: go run main.go
    networks:
      - default
      - sample-shared
  graphql-playground-server:
    build:
      context: ./graphql-playground-server
      dockerfile: Dockerfile
    ports:
      - '0.0.0.0:8082:8080'
    volumes:
      - ./graphql-playground-server:/app
    links:
      - server
    networks:
      - default
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5003:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    depends_on:
      - postgres
    networks:
      - default
networks:
  sample-shared:
    external: true