version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: todo-postgresql
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5050:5432'
    volumes:
      - /var/lib/postgresql/data
      - ./src/db-init:/docker-entrypoint-initdb.d/
  server:
    build:
      context: ./src
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - '0.0.0.0:8081:8080'
    volumes:
      - ./src:/app
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  graphql-playground-server:
    build:
      context: ./graphql-playground-src
      dockerfile: Dockerfile
    ports:
      - '0.0.0.0:8082:8080'
    volumes:
      - ./graphql-playground-src:/app
    links:
      - server